### ISSUE TITLE
Active Record Associations

### ISSUE THREAD

**Issue by mandytrex** [mandytrex/workout_buddy#1]
Hey, I have having a difficult time with one of my relationships.
![screen shot 2015-01-21 at 9 39 34 am](https://cloud.githubusercontent.com/assets/7253648/5837923/71502310-a151-11e4-8cef-91ce379e2dea.png)

Attached is a copy of my ERD and my most up to date code is pushed. The relationship I am confused with lies within my Groups Table, the attribute "coordinator_id" -- I would like for this to reference the user_id of the user who created the group. I've reviewed the Active Record associations/migrations documentation and I think my issue is not being certain of what exactly to search for within those documentations to resolve my issue. Let me know if I can explain this better in person

Thanks, Amanda

@htella @DrRobotmck

**Comment by htella** [comment]
Got this.

**Comment by htella** [comment]
Does a Group have_many Users and it also has a special User called a coordinator. Is that what you're going for?

**Comment by mandytrex** [comment]
Yes, I want the user who started the group to be saved as the coordinator for group. So I want that user's ID to be saved as the group's coordinator_id.

Is this possible?

@htella

**Comment by mandytrex** [comment]
And yes to your first question, a group has many users as well

**Comment by htella** [comment]
Yup, add an association on Groups that looks like

belongs_to :coordinator, :class_name => 'User', :foreign_key => 'coordinator_id'

Check this out for more of an example. Look the first answer.

http://stackoverflow.com/questions/2684843/belongs-to-with-class-name-option-fails

**Comment by mandytrex** [comment]
Thank you!
