### ISSUE TITLE
Rails form issue in users/new

### ISSUE THREAD

**Issue by mandytrex** [mandytrex/workout_buddy#3]
I am trying to add a drop down selection to my users/new _form view. The drop down should contain a list of all activities.

This is the porition of the form I am working with for it:
  <div class="input">
    <%= f.label :activity %>
    <%= f.collection_select(:user, :activity_id, Activity.all, :id, :name) %>
  </div> 

It's not working and I'm confused why. Any insight on how to properly set up the collection_select form helper? I am not really understanding the documentation.

Thanks
Amanda

@harimohanraj89 @htella @DrRobotmck

**Comment by htella** [comment]
is your latest code pushed?

**Comment by mandytrex** [comment]
yes, my latest code is pushed. in views/users/_form you will see i figured out how to add selections to fields in my form.

however, i want users to be able to select activities in the form of checkboxes. activities are seeded into my database in a many to many relationship with users

@htella

**Comment by harimohanraj89** [comment]
It looks like Rails has a convenient way to achieve this. 

http://apidock.com/rails/v4.0.2/ActionView/Helpers/FormOptionsHelper/collection_check_boxes
