### ISSUE TITLE
backbone view only working when i refresh page

### ISSUE THREAD

**Issue by mandytrex** [mandytrex/workout_buddy#4]
When I go to users/index it only shows all the user info when i refresh the page. I spoke with Emily and she said this has something to do with turbolinks?

Could I get some assistance with how to fix this issue?

Thanks
Amanda

@htella @DrRobotmck @harimohanraj89

**Comment by htella** [comment]
Yup try disabling turbolinks, I believe Hari wrote a guide. Let me see if I can find it for you.
