### ISSUE TITLE
twilio api

### ISSUE THREAD

**Issue by mandytrex** [mandytrex/workout_buddy#8]
I can't figure out how to set up my twilio api using this gem https://github.com/twilio/twilio-ruby

I have tried adding the information to config/initializers/twilio.rb and i have the keys saved to my bash profile. it seems like i followed their setup properly. my code is pushed i don't understand what i'm missing i know you said not to add the information to a model anymore is there a class example that you can recommend that might help me with this issue

@harimohanraj89 @htella @DrRobotmck 

``` ruby
require 'twilio-ruby'

Twilio.configure do |config|
  config.account_sid = ENV['TWILIO_ACCOUNT_SID']
  config.auth_token = auth_token = ENV['TWILIO_AUTH_TOKEN']
end
```

**Comment by harimohanraj89** [comment]
Reading.

**Comment by htella** [comment]
what's the error you get?

**Comment by htella** [comment]
sorry Hari, got to this at the same time, if you have some insight you can take it.

**Comment by harimohanraj89** [comment]
I have no insight. All yours.

**Comment by htella** [comment]
Amanda, can you type `env` in your command line and paste the result here.

**Comment by mandytrex** [comment]
##

**Comment by htella** [comment]
I looking for lines that show values for TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN

**Comment by htella** [comment]
ok type `source ~/.bash_profile` on the command line, and try `env` again

**Comment by mandytrex** [comment]
##

**Comment by htella** [comment]
ok see how we have entries for TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN now, but there are no value to the right side of the = sign. Something is not right in your .bash_profile, can you paste the section where you set the API keys in there?

**Comment by mandytrex** [comment]
Yes I see that, but I set it up the same way I have set up other API keys in the past so the error doesn't make sense to me, below is how i have it entered in my .bash_profile

#TWILIO API INFORMATION
export TWILIO_ACCOUNT_SID='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
export TWILIO_AUTH_TOKEN='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

**Comment by htella** [comment]
hmm, that looks good. Here's a blind guess. Can you close your terminal and open it back up, and check `env` again.

**Comment by mandytrex** [comment]
##

**Comment by mandytrex** [comment]
i still am unable to test if the setup is correct in my rails console

**Comment by htella** [comment]
hmm, what's the error, what exactly are you trying?

**Comment by htella** [comment]
btw going to delete the output of env here so your keys are not up on here.

**Comment by mandytrex** [comment]
do i have to also create a model after adding to my config file
i am entering the below into my rails console:
@client = Twilio::REST::Client.new

and i get this error:
ArgumentError: Account SID and auth token are required
from /Users/Owner/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/twilio-ruby-3.14.4/lib/twilio-ruby/rest/client.rb:154:in `initialize'

**Comment by mandytrex** [comment]
but i have added this information to config/initializers/twilio.rb as the below 

require 'twilio-ruby'

  account_sid = ENV['TWILIO_ACCOUNT_SID']
  auth_token = ENV['TWILIO_AUTH_TOKEN']

**Comment by htella** [comment]
should I be looking at the twillio_goals branch?

**Comment by mandytrex** [comment]
i pushed it to master because the only thing i changed is adding the file to config/initializers/twilio.rb

**Comment by htella** [comment]
ok, looking...

**Comment by htella** [comment]
hmm, I don't see it in master, the last commit was 2 days ago.

**Comment by htella** [comment]
on your computer are you working on a branch called `twillio_goals`?

**Comment by mandytrex** [comment]
i have been committing all weekend ugh i am not sure now i have to figure out what i have been doing wrong

**Comment by mandytrex** [comment]
no i am on master now

**Comment by htella** [comment]
hey I see all your recent changes on master now. 

let me check it out.

**Comment by htella** [comment]
try fixing this small thing in your initializer, you have an extra variable when setting the config.auth_token

``` ruby
Twilio.configure do |config|
  config.account_sid = ENV['TWILIO_ACCOUNT_SID']
  config.auth_token = auth_token = ENV['TWILIO_AUTH_TOKEN']
end
```

**Comment by mandytrex** [comment]
i have a ton of other changes that i have been pushing and nothing is on my github

**Comment by htella** [comment]
ok lets, figure it out.

**Comment by mandytrex** [comment]
i found that error changed it and pushed it 10 minutes ago :( this means nothing that i have done at all is really being pushed

**Comment by htella** [comment]
So you are working on master locally, and you push by doing `git push`? 

Can you make a new commit on master with just some dummy change. And then do a `git push` and paste the output here?

**Comment by htella** [comment]
can you also run `cat .git/config` paste the output here.

**Comment by mandytrex** [comment]
i have been working on branches and master - i commit the changes and push from branch then go to master and do git merge branch name

**Comment by htella** [comment]
ok can you switch to master, then do a `git push` and copy what you get as output here.

**Comment by mandytrex** [comment]
Owner ~/wdi/Repos/workout_buddy on master
$ git push
To git@github.com:mandytrex/workout_buddy.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@github.com:mandytrex/workout_buddy.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Owner ~/wdi/Repos/workout_buddy on master
$

**Comment by htella** [comment]
ok let's do a `git pull` and paste the output please

**Comment by mandytrex** [comment]
Owner ~/wdi/Repos/workout_buddy on master
$ git pull
remote: Counting objects: 2, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 2 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (2/2), done.
From github.com:mandytrex/workout_buddy
   bb9cc5f..c4a9221  activity_checkboxes -> origin/activity_checkboxes
   0da01a7..77ec474  master     -> origin/master
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details

```
git pull <remote> <branch>
```

If you wish to set tracking information for this branch you can do so with:

```
git branch --set-upstream-to=<remote>/<branch> master
```

Owner ~/wdi/Repos/workout_buddy on master
$

**Comment by htella** [comment]
let's do `git pull origin master`

**Comment by mandytrex** [comment]
Owner ~/wdi/Repos/workout_buddy on master
$ git pull origin master
From github.com:mandytrex/workout_buddy
- branch            master     -> FETCH_HEAD
  Already up-to-date!
  Merge made by the 'recursive' strategy.
  Owner ~/wdi/Repos/workout_buddy on master
  $

**Comment by htella** [comment]
cool now can you try `git push`

**Comment by mandytrex** [comment]
Owner ~/wdi/Repos/workout_buddy on master
$ git push
Counting objects: 9, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (9/9), done.
Writing objects: 100% (9/9), 1.05 KiB | 0 bytes/s, done.
Total 9 (delta 7), reused 0 (delta 0)
To git@github.com:mandytrex/workout_buddy.git
   77ec474..0c0271a  master -> master
Owner ~/wdi/Repos/workout_buddy on master
$

**Comment by htella** [comment]
cool now your latest changes are on github

**Comment by mandytrex** [comment]
thank you

**Comment by htella** [comment]
so if you do merges your way where you switch to master the do the merge, make sure you keep pushing master up to github by switching to the master branch and doing a `git push`

Also when you work this way, you don't need to mess with pull requests at all. You are doing it all locally on your machine.

**Comment by mandytrex** [comment]
Thank you I had a mini heartattack thought I was going to lose everything

getting this in my console now - I think this means it is recognizing my configuration?

[2] workout_buddy(main)> @client = Twilio::REST::Client.new
=> <Twilio::REST::Client @account_sid=AC80e8013a2db7c4a4cf808e34312cc832>

**Comment by mandytrex** [comment]
[2] workout_buddy(main)> @client = Twilio::REST::Client.new
=> <Twilio::REST::Client @account_sid=AC80e8013a2db7c4a4cf808e34312cc832>

**Comment by mandytrex** [comment]
![image](https://cloud.githubusercontent.com/assets/7253648/5927562/52c82c40-a641-11e4-8ffe-260d6a2f5ec2.png)

**Comment by htella** [comment]
cool, I think that means it's working

**Comment by htella** [comment]
or at least your keys are working

**Comment by htella** [comment]
Keep calm, and code on. Gonna close this issue for now. Feel free to open it up again.
